
/* Copyright (c) 2014-2015, Human Brain Project
 *                          Daniel Nachbaur <daniel.nachbaur@epfl.ch>
 *                          Juan Hernando <jhernando@fi.upm.es>
 *                          Grigori Chevtchenko <grigori.chevtchenko@epfl.ch>
 */

#ifndef ZEQ_HBP_VOCABULARY_H
#define ZEQ_HBP_VOCABULARY_H

#include <zeq/types.h>
#include <zeq/api.h>

#include <zeq/hbp/camera_zeq_generated.h>
#include <zeq/hbp/imageJPEG_zeq_generated.h>
#include <zeq/hbp/lookupTable1D_zeq_generated.h>
#include <zeq/hbp/selections_zeq_generated.h>

namespace zeq
{
namespace hbp
{
namespace data
{

/**
 * This structure holds informations about JPEG images.
 * It has the size infomations and the image data, data is a pointer
 * to avoid copy. The data pointer is only valid as long as the zeq Event
 * or rendering resource internal event with image data stays alive.
 */
struct ImageJPEG
{
    ImageJPEG( const uint32_t sizeInBytes, const uint8_t* data )
        : _sizeInBytes( sizeInBytes )
        , _data( data )
    {}
    uint32_t getSizeInBytes() const { return _sizeInBytes; }
    const uint8_t* getDataPtr() const { return _data; }

private:
    const uint32_t _sizeInBytes;
    const uint8_t* _data;
};

}

/**
 * Serialize the given JPEG image into an Event of type EVENT_IMAGEJPEG.
 * @param image the JPEG image.
 * @return the serialized event.
 */
ZEQ_API Event serializeImageJPEG( const data::ImageJPEG& image );

/**
 * Deserialize the given EVENT_IMAGEJPEG event into an JPEG image.
 * @param event the zeq EVENT_IMAGEJPEG.
 * @return the jpeg image.
 */
ZEQ_API data::ImageJPEG deserializeImageJPEG( const Event& event );

/**
 * Serialize the given camera matrix into an Event of type EVENT_CAMERA.
 * The matrix to be serialized and sent to other instances is the one
 * used in the application to transform from world coordinate space into
 * camera space. Microns are assumed as unit and it has the BBP circuit
 * as reference.
 * @param matrix the 4x4 camera matrix in OpenGL data layout.
 * @return the serialized event.
 */
ZEQ_API Event serializeCamera( const std::vector< float >& matrix );

/**
 * Deserialize the given camera event into the 4x4 matrix.
 * The matrix received and deserialized is the one used in the application
 * to transform from world coordinate space into camera space.
 * Microns are assumed as unit and it has the BBP circuit as reference.
 * @param camera the camera event generated by serializeCamera().
 * @return the 4x4 camera matrix in OpenGL data layout.
 */
ZEQ_API std::vector< float > deserializeCamera( const Event& event );

/**
 * Serialize the given neuron selection into an Event of type
 * EVENT_SELECTED_IDS.
 * @param selection vector of neuron GIDs (uint).
 * @return the serialized event.
 */
ZEQ_API
Event serializeSelectedIDs( const std::vector< unsigned int >& ids );

/**
 * Deserialize the given neuron selection event into the vector of neuron GIDs.
 * @param event a selection event generated by serializeSelection().
 * @return the vector of neuron GIDs (uint).
 */
ZEQ_API
std::vector< unsigned int > deserializeSelectedIDs( const Event& event );

/**
 * Serialize the given selection into an Event of type EVENT_TOGGLE_ID_REQUEST.
 * @param ids vector of neuron GIDs (uint).
 * @return the serialized event.
 */
ZEQ_API
Event serializeToggleIDRequest( const std::vector< unsigned int >& ids );

/**
 * Deserialize an toggle selection request event into the vector of neuron GIDs.
 * @param event an event generated by serializeToggleIDRequest().
 * @return the vector of neuron GIDs (uint).
 */
ZEQ_API
std::vector< unsigned int > deserializeToggleIDRequest( const Event& event );

/**
 * Serialize the given lookup table into an Event of type EVENT_LOOKUPTABLE1D.
 * The lookup table consists of 4 times 256 bytes, interleaved in r,g,b,a
 * layout. It is used to map intensity values onto a color, e.g., in direct
 * volume rendering.
 * @param lut the 1024 byte lookup table.
 * @return the serialized event.
 */
ZEQ_API Event serializeLookupTable1D( const std::vector< uint8_t >& lut );

/**
 * Deserialize the given 1D lookup table.
 * @param camera the camera event generated by serializeCamera().
 * @return the 1024 byte lookup table
 * @sa serializeLookupTable1D()
 */
ZEQ_API std::vector< uint8_t > deserializeLookupTable1D( const Event& event );

}
}
#endif
